global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['collector:8889']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'backend-service'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend:8080']
    metrics_path: /metrics
    scrape_interval: 10s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093